---
- hosts: 10.0.1.1
  ansible_python_interpreter: /usr/local/bin/python2.7
  remote_user: 'root'
  connection: paramiko
  collections:
   - pfsensible.core
  vars:
    
  tasks:
    - name: Add simple demo tunnel
      pfsensible.core.ipsec:
       state: present
       descr: demo_tunnel
       interface: wan
       iketype: ikev2
       authentication_method: pre_shared_key
       preshared_key: example_pre_shared_key
